FROM mysql

EXPOSE 3307

# 4 now...
#ENV MYSQL_DATABASE toolbox-transation-db
ENV MYSQL_DATABASE db_mjukvaru_usermicroservice
#ENV MYSQL_USER mysql
#ENV MYSQL_PASSWORD mysql
#ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
ENV MYSQL_TCP_PORT 3307
ENV MYSQL_ROOT_PASSWORD my-secret-pw

#RUN
#ENTRYPOINT ["/bin/sh", "-c", "mysql"]
#CMD ["mysql"]
